platform :osx, '10.13'

target 'Trivia' do
  use_frameworks!

  # Pods for MyApp 

  target 'TriviaTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'ApprovalTests_Swift', :git => 'https://github.com/approvals/ApprovalTests.Swift.git'
  end

end
